services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: zapsign
      POSTGRES_USER: zapsign
      POSTGRES_PASSWORD: zapsign
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
