# Generated by Django 4.2.14 on 2025-08-06 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('markdown', 'markdown'), ('url_pdf', 'url_pdf')], default='markdown', max_length=20)),
                ('markdown_text', models.TextField(blank=True, default='')),
                ('pdf_url', models.URLField(blank=True, default='')),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='documents.document')),
            ],
        ),
    ]
